version: '3.8'

services:
    node:
        build:
            context: ./docker/node
        #Needed for bash scripts to access environment variables
        env_file:
            - .env
        ports:
            - '3000:3000'
        volumes:
            - ./:/var/www/html
